# Generated by Django 4.0.3 on 2022-04-09 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(blank=True, choices=[('Phone_number', 'Phone'), ('E_Mail', 'Email')], default='Phone_number', max_length=12)),
                ('receiver', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
