# Generated by Django 4.0.3 on 2022-04-09 15:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otprequest_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=users.models.otp_generate, max_length=6),
        ),
    ]
